/** @type {import('next').NextConfig} */
const REDIRECT_MAP = [
  // CSV Fixer
  "/csv-fixer/add-column",
  "/csv-fixer/remove-column",
  "/csv-fixer/rename-column",
  "/csv-fixer/reorder-columns",
  "/csv-fixer/merge-columns",
  "/csv-fixer/split-column",
  "/csv-fixer/calculate-column",
  "/csv-fixer/fix-delimiter",
  "/csv-fixer/auto-detect-delimiter",
  "/csv-fixer/normalize-headers",
  "/csv-fixer/lowercase-headers",
  "/csv-fixer/trim-whitespace",
  "/csv-fixer/fill-missing-values",
  "/csv-fixer/drop-null-rows",
  "/csv-fixer/deduplicate-rows",
  "/csv-fixer/type-inference",
  "/csv-fixer/cast-column",
  "/csv-fixer/date-normalization",
  "/csv-fixer/encoding-fix",
  "/csv-fixer/escape-quotes",
  // Data Cleaning
  "/data-cleaning/remove-outliers",
  "/data-cleaning/impute-mean",
  "/data-cleaning/impute-median",
  "/data-cleaning/impute-mode",
  "/data-cleaning/standardize-values",
  "/data-cleaning/normalize-text",
  "/data-cleaning/fix-typos",
  "/data-cleaning/regex-replace",
  "/data-cleaning/remove-invalid-rows",
  "/data-cleaning/schema-validation",
  "/data-cleaning/range-validation",
  "/data-cleaning/uniqueness-check",
  "/data-cleaning/null-analysis",
  "/data-cleaning/consistency-check",
  // Query to CSV
  "/query-to-csv/natural-language",
  "/query-to-csv/sql-like",
  "/query-to-csv/hive",
  "/query-to-csv/spark-sql",
  "/query-to-csv/presto",
  "/query-to-csv/trino",
  "/query-to-csv/postgres",
  "/query-to-csv/mysql",
  "/query-to-csv/mongodb",
  "/query-to-csv/elasticsearch",
  "/query-to-csv/parquet",
  "/query-to-csv/orc",
  // Notebook
  "/notebook/run-cell",
  "/notebook/run-all",
  "/notebook/stop-kernel",
  "/notebook/restart-kernel",
  "/notebook/clear-output",
  "/notebook/save-checkpoint",
  "/notebook/convert-to-script",
  "/notebook/convert-to-html",
  "/notebook/convert-to-pdf",
  "/notebook/parameterize",
  "/notebook/schedule-run",
  "/notebook/version-diff",
  "/notebook/trust-notebook",
  // AI Notebook
  "/ai-notebook/explain-cell",
  "/ai-notebook/refactor-code",
  "/ai-notebook/optimize-query",
  "/ai-notebook/generate-sql",
  "/ai-notebook/generate-pyspark",
  "/ai-notebook/auto-comment",
  "/ai-notebook/find-bug",
  "/ai-notebook/explain-error",
  "/ai-notebook/suggest-visualization",
  "/ai-notebook/data-summary",
  "/ai-notebook/schema-inference",
  "/ai-notebook/code-translation",
  // Spark
  "/spark/load-csv",
  "/spark/load-parquet",
  "/spark/load-orc",
  "/spark/write-csv",
  "/spark/write-parquet",
  "/spark/cache-dataframe",
  "/spark/repartition",
  "/spark/coalesce",
  "/spark/join-optimizer",
  "/spark/window-functions",
  "/spark/udf-register",
  "/spark/streaming-ingest",
  "/spark/streaming-aggregate",
  // Hive
  "/hive/create-table",
  "/hive/drop-table",
  "/hive/alter-table",
  "/hive/load-data",
  "/hive/partition-add",
  "/hive/partition-repair",
  "/hive/partition-prune",
  "/hive/bucket-table",
  "/hive/serde-detect",
  "/hive/query-optimizer",
  "/hive/statistics-analyze",
  // ETL
  "/etl/extract",
  "/etl/transform",
  "/etl/load",
  "/etl/incremental-load",
  "/etl/full-refresh",
  "/etl/schema-mapping",
  "/etl/column-mapping",
  "/etl/data-enrichment",
  "/etl/lookup-join",
  "/etl/surrogate-key",
  "/etl/change-data-capture",
  // Dataset
  "/dataset/upload",
  "/dataset/download",
  "/dataset/preview",
  "/dataset/profile",
  "/dataset/version",
  "/dataset/lineage",
  "/dataset/metadata",
  "/dataset/sample",
  "/dataset/statistics",
  "/dataset/delete",
  // Visualization
  "/visualization/line-chart",
  "/visualization/bar-chart",
  "/visualization/pie-chart",
  "/visualization/histogram",
  "/visualization/boxplot",
  "/visualization/heatmap",
  "/visualization/scatter",
  "/visualization/time-series",
  "/visualization/dashboard",
  "/visualization/export",
  // ML
  "/ml/train",
  "/ml/validate",
  "/ml/test",
  "/ml/cross-validation",
  "/ml/feature-engineering",
  "/ml/feature-selection",
  "/ml/scaling",
  "/ml/encoding",
  "/ml/hyperparameter-search",
  "/ml/model-compare",
  "/ml/model-export",
  // Ops
  "/ops/job-status",
  "/ops/job-logs",
  "/ops/job-retry",
  "/ops/job-cancel",
  "/ops/resource-usage",
  "/ops/cost-estimation",
  "/ops/alerting",
  "/ops/audit-log",
  "/ops/access-control",
  "/ops/secret-management",
  // Governance
  "/governance/data-access",
  "/governance/column-masking",
  "/governance/row-filtering",
  "/governance/pii-detection",
  "/governance/pii-redaction",
  "/governance/retention-policy",
  "/governance/compliance-report",
];

const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.jsdelivr.net",
        pathname: "/**",
      },
    ],
  },
  async redirects() {
    return REDIRECT_MAP.map((path) => ({
      source: path,
      destination: "/",
      permanent: true,
    }));
  },
};

export default nextConfig;
